authConfig:
    consumerKey: IuyRbIuFMdi7QDr2K3C11ARJE (Dummy)
    consumerSecret: UAeLMrQDDrHaAgPcotNa2I9Xdlx0pujW9LAy6AYTYks9idzLs0 (Dummy)
    accessToken: 894411261248548864-xsXAH4sKNzcrgmIqzVlD78P1Vs9jZ5C (Dummy)
    accessTokenSecret: 4O9tG61BQBIJa6siJ4FZ2xvcj0owM5IvPdC129DyJwake (Dummy)